FROM node:14-alpine AS builder
RUN apk update && \
    apk add npm && \
    npm install -g purify-css minify
ADD . /work
WORKDIR /work
RUN sh ./build-nginx.sh && \
    rm -rf ./.git ./.databases ./application ./deploy ./system ./.gitignore ./.gitlab-ci.yml ./1.obaju-2-1-1.zip ./build-nginx.sh ./Dockerfile ./index.php ./robots.txt ./sitemap.xml ./README.md ./output ./id_rsa

FROM alpine:3.12.3
RUN apk update && \
    apk add git openssh
ADD ./id_rsa /root/.ssh/id_rsa
WORKDIR /work
RUN chmod 700 /root/.ssh/id_rsa && \
    git config --global user.name "farmerpiac" && \
    git config --global user.email "info@farmerpiac.hu" && \
    ssh-keyscan github.com >> /root/.ssh/known_hosts && \
    git clone git@github.com:farmerpiac/assets.farmerpiac.hu.git && \
    rm -rf /work/assets.farmerpiac.hu/assets
COPY --chown=1000:1000 --from=builder /work ./assets.farmerpiac.hu
WORKDIR /work/assets.farmerpiac.hu
RUN if [ $(git status | wc -l) -ne 4 ];then git add -A;git commit -m"$(date +%s) git push upload";git push origin master; fi